{% set name = "seamm-dashboard-client" %}
{% set version = "2025.10.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/seamm_dashboard_client-{{ version }}.tar.gz
  sha256: 1fc3979aac250d79098df4e35633d85ca816b6fa6df4a2eaa163fb454b27a016

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - requests-toolbelt

test:
  imports:
    - seamm_dashboard_client
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/molssi-seamm/seamm_dashboard_client
  summary: A Python client for the SEAMM Dashboard RESTful API.
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - paulsaxe
